/*-*- mode: c;-*-*/
#if !defined(_all_types_inc_)
#define _all_types_inc_
/***************************
 **
 ** Purpose
 **   this include all node types to may them easier to use
 **/

#include "count.h"
#include "hash.h"
#include "input.h"
#include "integer.h"
#include "output.h"
#include "pair.h"
#include "primitive.h"
#include "set.h"
#include "symbol.h"
#include "text.h"


/* */
#include "node.h"
/* */
/***************************
 ** end of file
 **************************/
#endif
