
TARGETS := all
TARGETS += enki
TARGETS += lib   
TARGETS += test  
TARGETS += asm   
TARGETS += units 
TARGETS += atoms 
TARGETS += install
TARGETS += install.bin
TARGETS += install.inc
TARGETS += install.lib 
TARGETS += checkpoint 
TARGETS += depends 
TARGETS += clean 
TARGETS += scrub 
TARGETS += test 
TARGETS += obj 
TARGETS += checkpoint

$(TARGETS) :
	@make -C .. $@


