
TARGETS :=
TARGETS += asm   
TARGETS += atoms 
TARGETS += checkpoint
TARGETS += clean 
TARGETS += depends 
TARGETS += enki
TARGETS += install
TARGETS += install.bin
TARGETS += install.inc
TARGETS += install.lib 
TARGETS += lib   
TARGETS += obj 
TARGETS += scrub 
TARGETS += test  
TARGETS += units 

all :
	@make -C .. $@

$(TARGETS) :
	@make -C .. $@


